path_builder:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    map_topic: "/map"
    initial_pose_topic: "/initialpose"
    drive_topic: "/vesc/input/navigation"
path_follower:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    drive_filter_topic: "/drive_filter"
    drive_topic: "/vesc/input/navigation"
